-- AlterTable
ALTER TABLE "schedules" ADD COLUMN     "ecThreshold" DOUBLE PRECISION NOT NULL DEFAULT -1,
ADD COLUMN     "imageData" TEXT,
ADD COLUMN     "kThreshold" DOUBLE PRECISION NOT NULL DEFAULT -1,
ADD COLUMN     "moistureThreshold" DOUBLE PRECISION NOT NULL DEFAULT -1,
ADD COLUMN     "nThreshold" DOUBLE PRECISION NOT NULL DEFAULT -1,
ADD COLUMN     "pHThreshold" DOUBLE PRECISION NOT NULL DEFAULT -1,
ADD COLUMN     "pThreshold" DOUBLE PRECISION NOT NULL DEFAULT -1,
ADD COLUMN     "plantName" TEXT,
ADD COLUMN     "temperatureThreshold" DOUBLE PRECISION NOT NULL DEFAULT -1;
