name: SSH to VPS - Auto deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to VPS
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd nestjs-api-thesis/
          ./script_update.sh
        host: ${{ secrets.HOST }}
        user: root
        key: ${{ secrets.SSH_PRIVATE_KEY}}

