name: SSH to VPS - Auto deploy

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install SSH
        run: sudo apt-get install openssh-client -y

      - name: Setup SSH key
        run: |
          ssh-keyscan -t rsa 45.117.169.7 >> ~/.ssh/known_hosts
          cat ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH to VPS
        run: |
          ssh -i ~/.ssh/id_rsa root@45.117.169.7
          cd nestjs-api-thesis/ && ./script_update.sh
          exit
