name: SSH to VPS - Auto deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        username: root
        host: 45.117.169.7
        password: ${{ secrets.SSH_PASSWORD }}
        script: 'cd nestjs-api-thesis/ && ./script_update.sh'
